=== forge-engine/forge-starter/engine/Core/Schema/module-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Forge Module Schema",
	"description": "Schema for Forge module configuration files.",
	"type": "object",
	"properties": {
		"name": {
			"type": "string",
			"description": "The name of the module.",
			"examples": [
				"forge-basic-router"
			]
		},
		"version": {
			"type": "string",
			"description": "The version of the module.",
			"pattern": "^\\d+\\.\\d+\\.\\d+$",
			"examples": [
				"1.0.0"
			]
		},
		"description": {
			"type": "string",
			"description": "A description of the module.",
			"examples": [
				"Forge basic router example"
			]
		},
		"author": {
			"type": "string",
			"description": "Author name of the module",
			"examples": [
				"Jhon Doe"
			]
		},
		"license": {
			"type": "string",
			"description": "Module license",
			"examples": [
				"MIT",
				"GPL"
			]
		},
		"type": {
			"type": "string",
			"description": "The type of the module.",
			"examples": [
				"router"
			]
		},
		"order": {
			"type": "integer",
			"description": "The order in which the module should be loaded.",
			"examples": [
				3
			]
		},
		"cli": {
			"type": "object",
			"properties": {
				"commands": {
					"type": "array",
					"items": {
						"type": "string",
						"description": "CLI commands provided by the module.",
						"examples": [
							"route:list"
						]
					},
					"description": "List of CLI commands."
				}
			},
			"description": "CLI configuration for the module."
		},
		"tags": {
			"type": "array",
			"items": {
				"type": "string",
				"description": "Tags associated with the module.",
				"examples": [
					"router"
				]
			},
			"description": "List of tags."
		},
		"config": {
			"type": "object",
			"properties": {
				"defaults": {
					"type": "object",
					"description": "Default configuration values for the module."
				}
			},
			"description": "Configuration options for the module."
		}
	},
	"required": [
		"name",
		"version",
		"description",
		"type"
	]
}

=== forge-engine/forge-starter/modules/ForgePackageManager/forge.json
{
	"$schema": "./../../engine/Core/Schema/module-schema.json",
	"name": "forge-package-manager",
	"version": "0.1.0",
	"description": "A Package Manager By Forge",
	"type": "package-manager",
	"order": 0,
	"cli": {
		"commands": [
			"install:module",
			"remove:module"
		]
	},
	"tags": [],
	"config": {
		"defaults": {}
	},
	"author": "Forge Team",
	"license": "MIT"
}
